logging:
  level: INFO
  appenders:
    - type: console
      threshold: DEBUG
    - type: file
      currentLogFilename: ./logs/GridFSFileExtractor.log
      archivedLogFilenamePattern: ./logs/GridFSFileExtractor-%d.log.gz
      archivedFileCount: 5
mongodbFilePath: /Users/sepp/Customers/asml/fileExporter/data
mongodbHostname: localhost
mongodbPort: 27017
mongodbDatabaseName: test
mongodbUser:
mongodbPassword:
mongodbAuthenticationDb: admin


